global:
  cattle:
    systemDefaultRegistry: ''
  kubectl:
    repository: rancher/kubectl
    tag: v1.20.2
    pullPolicy: IfNotPresent
  imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
pluginServer:
  image:
    repository: jordojordo/ui-plugin-charts
    pullPolicy: Always
    tag: 0.1.7
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  deployment:
    replicas: 1
  resources: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
plugin:
  enabled: true
  versionOverride: ''
  noCache: false
